---
- name: Clone personal config repo
  ansible.builtin.git:
    repo: https://github.com/arthu-pr/dotfiles
    dest: '{{ ansible_env.HOME }}/config'
    version: main
  when: run_install | default(false)

- name: Run script to set up symlinks
  ansible.builtin.shell: |
    cd "{{ ansible_env.HOME }}/config"
    { printf '\n'; printf '\n'; yes y; } | bash ./set_symbolic_links.sh
  register: dotfiles_setup_script_result
  changed_when: dotfiles_setup_script_result.rc != 0
  args:
    executable: /bin/bash

- name: Debug setup script output
  ansible.builtin.debug:
    msg: '{{ dotfiles_setup_script_result.stdout_lines }}'
  when: dotfiles_setup_script_result.stdout is defined

- name: Update config files
  ansible.builtin.git:
    repo: https://github.com/arthu-pr/dotfiles
    dest: '{{ ansible_env.HOME }}/config'
    version: main
  when: run_update | default(false)
