---
# This task file is used to find the current npm executable path
# As nvm is used, the npm executable location can change based on the node version
# See https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html#parameter-executable

- name: Source nvm and find the node executable path
  ansible.builtin.shell: |
    source ~/.nvm/nvm.sh &&
    nvm which node
  register: node_path_result
  changed_when: node_path_result.rc != 0
  args:
    executable: /bin/bash

- name: Ensure node executable path is found
  ansible.builtin.fail:
    msg: Failed to find node executable path
  when: node_path_result.rc != 0

- name: Set node path fact
  ansible.builtin.set_fact:
    nvm_node_pm2_node_path: '{{ node_path_result.stdout | trim }}'

- name: Set node directory fact
  ansible.builtin.set_fact:
    nvm_node_pm2_node_dir: '{{ node_path | dirname }}'

- name: Set npm path fact
  ansible.builtin.set_fact:
    nvm_node_pm2_npm_path: '{{ node_dir }}/npm'
